# Generated by Django 5.0.7 on 2024-07-24 05:01

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=300)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Business_name', models.CharField(max_length=255)),
                ('product_img', models.ImageField(upload_to=None)),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description_ser', models.CharField(max_length=300)),
                ('highestAmount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('location', models.CharField()),
                ('lowestAmount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('serviceCategory', models.CharField(max_length=50)),
                ('serviceName', models.CharField(max_length=50)),
                ('selectedEventTypes', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), size=None)),
                ('selectedServices', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), size=None)),
                ('images', models.ImageField(upload_to='./media')),
                ('videos', models.FileField(upload_to='./media')),
            ],
        ),
    ]
