# Generated by Django 5.0.7 on 2024-07-24 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('businessName', models.CharField(max_length=255)),
                ('business_logo', models.ImageField(upload_to='./media')),
                ('owner_name', models.CharField(max_length=50)),
                ('phone_number', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gst_number', models.CharField(max_length=15)),
                ('pan_number', models.CharField(max_length=10)),
            ],
        ),
    ]
